{{ if eq .Values.knServing.use false }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deployment.name }}
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.containerPort }}
    name: http
  selector:
    app: {{ .Values.deployment.name }}
  type: LoadBalancer
status:
  loadBalancer: {}
{{ end }}