# Source: helloworld-nodejs-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld-nodejs
  name: helloworld-nodejs-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: helloworld-nodejs
  type: LoadBalancer
status:
  loadBalancer: {}
---
# Source: helloworld-nodejs-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld-nodejs
  name: helloworld-nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-nodejs
  strategy: {}
  template:
    metadata:
      labels:
        app: helloworld-nodejs
    spec:
      containers:
      - image: "dleurs/helloworld-nodejs:1.0.1"
        name: helloworld-nodejs
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: NODE_ENV
            value: "development"
        resources: {}
status: {}

